### ISSUE TITLE
Problems with menubar theming

### ISSUE THREAD

**Issue by LaraCraft93** [evolve-os/budgie-desktop#140] opened 2014-12-19 10:45 UTC
1. Configurations needed to reproduce:
   GNOME Panel theme integration = false
   Dark theme = false
   MenuBar Applet

   Foreground in Gtk.ImageMenuItem is always white while GNOME panel theme integration is disabled, regardless of the current theme settings (see with dark theme disabled, the foreground and background is white).

2. Configurations needed to reproduce:
   MenuBar Applet

   Menubar Applet don't respect panel transparency without explicitly set override_background_color to a transparent Gdk.RGBA. But that does not seem to be the real fix because if I replace mutter (budgie-wm) by another window manager, the menubar automagically shows a transparent background.

**Comment by ikeydoherty** [comment] 2015-02-09 23:29
The menu applet is only provided for GNOME compatibility mode, that's it. If a context-sensitive approach is required then a patch needs to come my way :) I'm closing for now as this is the intended behaviour, its meant to integrate with the old GNOME Panel theming and act the same.

**Closed by ikeydoherty** 2015-02-09 23:29 UTC
